# Generated by Django 4.2.8 on 2025-10-19 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dichvu', models.CharField(max_length=100)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mo_ta', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DV_LichHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dichvu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TK.dichvu')),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('dia_chi', models.CharField(max_length=255)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('gioi_tinh', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1)),
                ('ngay_tham_gia', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuanTriVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('quyen_han', models.CharField(max_length=100)),
                ('ngay_tao_quyen', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dang_nhap', models.CharField(max_length=100, unique=True)),
                ('mat_khau', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TichDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_diem', models.IntegerField(default=0)),
                ('cap_bac', models.CharField(max_length=50)),
                ('id_khachhang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TK.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='ThuCung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thucung', models.CharField(max_length=100)),
                ('loai', models.CharField(max_length=100)),
                ('tuoi', models.IntegerField()),
                ('ghi_chu', models.TextField(blank=True)),
                ('id_khachhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TK.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(max_length=100)),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TK.quantrivien')),
            ],
        ),
        migrations.AddField(
            model_name='quantrivien',
            name='id_taikhoan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TK.taikhoan'),
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('dia_chi', models.CharField(max_length=255)),
                ('chuc_vu', models.CharField(max_length=100)),
                ('ngay_vao_lam', models.DateField()),
                ('id_taikhoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TK.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='LichHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_gio', models.DateTimeField()),
                ('trang_thai', models.CharField(choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Đã xác nhận', 'Đã xác nhận'), ('Hoàn thành', 'Hoàn thành'), ('Hủy', 'Hủy')], max_length=50)),
                ('ghi_chu', models.TextField(blank=True)),
                ('dich_vu', models.ManyToManyField(through='TK.DV_LichHen', to='TK.dichvu')),
                ('id_khachhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TK.khachhang')),
                ('id_nhanvien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TK.nhanvien')),
                ('id_thucung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TK.thucung')),
            ],
        ),
        migrations.CreateModel(
            name='KhieuNaiPhanHoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(choices=[('Chờ xử lý', 'Chờ xử lý'), ('Đang xử lý', 'Đang xử lý'), ('Đã phản hồi', 'Đã phản hồi'), ('Đã đóng', 'Đã đóng')], max_length=50)),
                ('phan_hoi', models.TextField(blank=True)),
                ('id_khachhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TK.khachhang')),
                ('id_nhanvien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TK.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='KhachHangThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai', models.CharField(choices=[('Đã đọc', 'Đã đọc'), ('Chưa đọc', 'Chưa đọc')], max_length=20)),
                ('ngay_nhan', models.DateTimeField(auto_now_add=True)),
                ('id_khachhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TK.khachhang')),
                ('id_thongbao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TK.thongbao')),
            ],
        ),
        migrations.AddField(
            model_name='khachhang',
            name='id_taikhoan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TK.taikhoan'),
        ),
        migrations.AddField(
            model_name='dv_lichhen',
            name='id_lichhen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TK.lichhen'),
        ),
    ]
