# Generated by Django 5.2.7 on 2025-11-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TK', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='gioi_tinh',
            field=models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1),
        ),
    ]
