# Generated by Django 5.2.7 on 2025-10-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TK', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='ho_ten',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
