# Generated by Django 5.2.7 on 2025-10-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TK', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thucung',
            name='can_nang',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
