# Generated by Django 5.2.7 on 2025-10-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TK', '0002_thucung_can_nang'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='ho_ten',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quantrivien',
            name='ho_ten',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
