# Generated by Django 5.2.7 on 2025-11-01 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TK', '0003_nhanvien_email_nhanvien_ho_ten_quantrivien_ho_ten'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuanTriVien',
        ),
    ]
