# Generated by Django 4.2.8 on 2025-11-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TK', '0004_delete_quantrivien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhanvien',
            name='chuc_vu',
        ),
    ]
