# Generated by Django 5.2.7 on 2025-11-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TK', '0004_delete_quantrivien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhanvien',
            name='chuc_vu',
        ),
    ]
