# Generated by Django 5.2.5 on 2025-11-14 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TK', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('id_tinnhan', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=64, null=True)),
                ('nguoi_gui', models.CharField(choices=[('khachhang', 'Khách hàng'), ('khach_vang_lai', 'Khách vãng lai'), ('nhanvien', 'Nhân viên'), ('admin', 'Quản trị viên'), ('bot', 'Hệ thống tự động')], max_length=20)),
                ('noi_dung', models.TextField()),
                ('thoi_gian_gui', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('id_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tinnhan_admin', to=settings.AUTH_USER_MODEL)),
                ('id_khachhang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tinnhan_khachhang', to='TK.khachhang')),
                ('id_nhanvien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tinnhan_nhanvien', to='TK.nhanvien')),
            ],
        ),
    ]
