# Generated by Django 4.2.8 on 2025-10-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhieunaiDanhgia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khieunai',
            name='hinh_anh',
        ),
        migrations.AddField(
            model_name='khieunai',
            name='minh_chung',
            field=models.FileField(blank=True, null=True, upload_to='minhchung/', verbose_name='Minh chứng (ảnh hoặc video)'),
        ),
    ]
