# Generated by Django 4.2.8 on 2025-10-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhieunaiDanhgia', '0002_remove_khieunai_hinh_anh_khieunai_minh_chung'),
    ]

    operations = [
        migrations.AddField(
            model_name='khieunai',
            name='phan_hoi',
            field=models.TextField(blank=True, null=True, verbose_name='Phản hồi / Ghi chú từ nhân viên'),
        ),
    ]
