# Generated by Django 4.2.8 on 2025-11-07 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KhieunaiDanhgia', '0003_khieunai_phan_hoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='khieunai',
            name='nhan_vien_phu_trach',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khieunai_phu_trach', to=settings.AUTH_USER_MODEL),
        ),
    ]
