# Generated by Django 5.2.5 on 2025-10-23 11:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DV', '0001_initial'),
        ('TK', '0003_nhanvien_email_nhanvien_ho_ten_quantrivien_ho_ten'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_dien_thoai', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải gồm đúng 10 chữ số.', regex='^\\d{10}$')], verbose_name='Số điện thoại')),
                ('thoi_gian', models.DateTimeField(help_text='Thời gian thực hiện dịch vụ.')),
                ('ghi_chu', models.TextField(blank=True, help_text='Ghi chú đặc biệt của khách hàng.')),
                ('trang_thai', models.CharField(choices=[('sap_toi', 'Sắp tới'), ('hoan_thanh', 'Hoàn thành'), ('huy', 'Đã hủy')], default='sap_toi', max_length=20)),
                ('danh_gia', models.CharField(blank=True, help_text='Đánh giá sau dịch vụ (nếu có).', max_length=255)),
                ('khieu_nai', models.TextField(blank=True, help_text='Khiếu nại của khách hàng (nếu có).')),
                ('khach_hang', models.ForeignKey(help_text='Khách hàng đặt lịch hẹn.', on_delete=django.db.models.deletion.CASCADE, to='TK.khachhang')),
                ('nhan_vien', models.ForeignKey(blank=True, help_text='Nhân viên phụ trách dịch vụ.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TK.nhanvien')),
                ('thu_cung', models.ForeignKey(help_text='Thú cưng được chăm sóc.', on_delete=django.db.models.deletion.CASCADE, to='TK.thucung')),
            ],
        ),
        migrations.CreateModel(
            name='DV_LichHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dich_vu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DV.dichvu')),
                ('lich_hen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LichHen.lichhen')),
            ],
        ),
    ]
