# Generated by Django 5.2.5 on 2025-10-21 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TK', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.DateTimeField(help_text='Thời gian thực hiện dịch vụ.')),
                ('dich_vu', models.CharField(help_text='Tên dịch vụ thực hiện.', max_length=200)),
                ('can_nang', models.CharField(blank=True, help_text='Cân nặng thú cưng (nếu có).', max_length=50)),
                ('ghi_chu', models.TextField(blank=True, help_text='Ghi chú đặc biệt của khách hàng.')),
                ('trang_thai', models.CharField(choices=[('sap_toi', 'Sắp tới'), ('hoan_thanh', 'Hoàn thành'), ('huy', 'Đã hủy')], default='sap_toi', max_length=20)),
                ('danh_gia', models.CharField(blank=True, help_text='Đánh giá sau dịch vụ (nếu có).', max_length=255)),
                ('khieu_nai', models.TextField(blank=True, help_text='Khiếu nại của khách hàng (nếu có).')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('khach_hang', models.ForeignKey(help_text='Khách hàng đặt lịch hẹn.', on_delete=django.db.models.deletion.CASCADE, to='TK.khachhang')),
                ('nhan_vien', models.ForeignKey(blank=True, help_text='Nhân viên phụ trách dịch vụ.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TK.nhanvien')),
                ('thu_cung', models.ForeignKey(help_text='Thú cưng được chăm sóc.', on_delete=django.db.models.deletion.CASCADE, to='TK.thucung')),
            ],
        ),
    ]
