# Generated by Django 5.2.7 on 2025-10-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LichHen', '0001_initial'),
    ]

    operations = [
    ]
