# Generated by Django 5.2.5 on 2025-10-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LichHen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichhen',
            name='danh_gia',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='khieu_nai',
        ),
        migrations.AddField(
            model_name='lichhen',
            name='ly_do_huy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
