# Generated by Django 5.2.5 on 2025-10-23 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DV', '0001_initial'),
        ('LichHen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichhen',
            name='can_nang',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='dich_vu',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='ngay_tao',
        ),
        migrations.CreateModel(
            name='DV_LichHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dich_vu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DV.dichvu')),
                ('lich_hen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LichHen.lichhen')),
            ],
        ),
    ]
