# Generated by Django 5.2.7 on 2025-11-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DV', '0001_initial'),
        ('LichHen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhen',
            name='dich_vu',
            field=models.ManyToManyField(help_text='Các dịch vụ được chọn trong lịch hẹn này.', related_name='lich_hens', through='LichHen.DV_LichHen', to='DV.dichvu'),
        ),
    ]
