# Generated by Django 5.2.7 on 2025-11-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LichHen', '0002_remove_lichhen_danh_gia_remove_lichhen_khieu_nai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhen',
            name='da_nhac',
            field=models.BooleanField(default=False, help_text='Đánh dấu nếu đã gửi thông báo nhắc lịch cho khách.'),
        ),
    ]
