# Generated by Django 5.2.5 on 2025-10-23 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LichHen', '0002_remove_lichhen_can_nang_remove_lichhen_dich_vu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhen',
            name='so_dien_thoai',
            field=models.CharField(default='0123456789', max_length=10, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải gồm đúng 10 chữ số.', regex='^\\d{10}$')], verbose_name='Số điện thoại'),
            preserve_default=False,
        ),
    ]
