# Generated by Django 5.2.7 on 2025-11-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LichHen', '0002_lichhen_dich_vu'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhen',
            name='ten_khach_vang_lai',
            field=models.CharField(blank=True, help_text='Tên khách hàng vãng lai nếu không có tài khoản.', max_length=100),
        ),
    ]
