# Generated by Django 5.2.7 on 2025-11-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LichHen', '0003_lichhen_ten_khach_vang_lai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichhen',
            name='dich_vu',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='ten_khach_vang_lai',
        ),
    ]
