# Generated by Django 5.2.7 on 2025-11-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DV', '0001_initial'),
        ('LichHen', '0004_remove_lichhen_dich_vu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhen',
            name='dich_vus',
            field=models.ManyToManyField(related_name='lich_hens', through='LichHen.DV_LichHen', to='DV.dichvu'),
        ),
    ]
