# Generated by Django 5.2.7 on 2025-10-29 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TB', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thongbao',
            options={'ordering': ['-ngay_tao']},
        ),
        migrations.AddField(
            model_name='thongbao',
            name='loai',
            field=models.CharField(choices=[('lich_hen', 'Lịch hẹn'), ('khieu_nai', 'Khiếu nại'), ('he_thong', 'Hệ thống')], default='he_thong', max_length=20),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='nguoi_gui',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='thongbao_gui', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='nguoi_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thongbao_nhan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='tieu_de',
            field=models.CharField(max_length=100),
        ),
    ]
