# Generated by Django 5.2.7 on 2025-11-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TB', '0002_alter_thongbao_options_thongbao_loai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongbao',
            name='dich_vu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thongbao',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='loai',
            field=models.CharField(choices=[('lich_hen', 'Lịch hẹn'), ('khieu_nai', 'Khiếu nại'), ('he_thong', 'Hệ thống')], default='lich_hen', max_length=20),
        ),
    ]
