# Generated by Django 5.2.7 on 2025-11-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TB', '0003_thongbao_dich_vu_thongbao_ghi_chu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongbao',
            name='link',
            field=models.CharField(blank=True, help_text='Đường dẫn khi người dùng bấm vào thông báo', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='loai',
            field=models.CharField(choices=[('lich_hen', 'Lịch hẹn'), ('khieu_nai', 'Khiếu nại'), ('he_thong', 'Hệ thống'), ('nhac_lich', 'Nhắc lịch')], default='lich_hen', max_length=20),
        ),
    ]
