# Generated by Django 5.2.7 on 2025-11-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TB', '0004_thongbao_link_alter_thongbao_loai'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongbao',
            name='doi_tuong_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
