# Generated by Django 5.2.7 on 2025-11-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TB', '0005_thongbao_doi_tuong_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongbao',
            name='loai',
            field=models.CharField(choices=[('lich_hen', 'Lịch hẹn'), ('khieu_nai', 'Khiếu nại'), ('he_thong', 'Hệ thống')], default='lich_hen', max_length=20),
        ),
    ]
