# Generated by Django 4.2.8 on 2025-11-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dichvu',
            name='gia',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá'),
        ),
    ]
